#  Copyright (c) Juniper Networks, Inc., 2025-2025.
#  All rights reserved.
#  SPDX-License-Identifier: MIT

name: Checks

on:
  push:

jobs:
  license-file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: echo "errors in this section might be resolved by reviewing https://github.com/chrismarget-j/apstrahub-configpack-example/blob/main/publisher_guide/license.md"
      - name: Check license headers
        run: ./.ci/scripts/check_license.sh
        env:
          COPYRIGHT_HOLDER: ${{ vars.COPYRIGHT_HOLDER }}
  signing-key-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: echo "errors in this section might be resolved by reviewing https://github.com/chrismarget-j/apstrahub-configpack-example/blob/main/publisher_guide/02_signing_key.md"
      - name: Import signing key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Sign test file
        run: |
          f=$(mktemp)
          dd if=/dev/urandom of=$f count=1
          gpg --default-key ${{ steps.import_gpg.outputs.fingerprint }} --passphrase-fd 0 --pinentry-mode=loopback --sign $f <<< $PASSPHRASE
          ls -l $f*
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
  tofu-permitted-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: echo "errors in this section might be resolved by reviewing https://github.com/chrismarget-j/apstrahub-configpack-example/blob/main/publisher_guide/tofu-guidelines.md"
      - name: Ensure files in pack/tofu look like *.tf
        run: .ci/scripts/non_tofu_files.sh pack/tofu
  tofu-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: echo "errors in this section might be resolved by reviewing https://github.com/chrismarget-j/apstrahub-configpack-example/blob/main/publisher_guide/tofu-guidelines.md"
      - name: OpenTofu - Setup Tofu
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
        with:
          tofu_version: 1.9.0
      - name: run tofu fmt
        run: ./.ci/scripts/tofu_fmt.sh
  terraform-config-inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22.5'
      - name: Install terraform-config-inspect
        run: go install github.com/hashicorp/terraform-config-inspect@d2d12f9a63bbb1fe34ea81ec84c9cb11d8514c17
      - name: Run terraform-config-inspect
        run: .ci/scripts/provider_block.sh pack/tofu
  check_underscores:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check for underscores in repository name
        run : .ci/scripts/underscores.sh
  check_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check manifest.yml file
        run : .ci/scripts/check_manifest.sh
